//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Pokemon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DynamicPokemons;

/**
 * Helper class for marshaling/unmarshaling PokemonSequence.
 **/
public final class PokemonSequenceHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Pokemon[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Pokemon.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Pokemon[] read(com.zeroc.Ice.InputStream istr)
    {
        final Pokemon[] v;
        final int len0 = istr.readAndCheckSeqSize(10);
        v = new Pokemon[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Pokemon.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Pokemon[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Pokemon[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            PokemonSequenceHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Pokemon[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Pokemon[] v;
            v = PokemonSequenceHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
