//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Pokemon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DynamicPokemons;

public interface PokemonInterfacePrx extends com.zeroc.Ice.ObjectPrx
{
    default Pokemon[] sortByHealth(Pokemon[] pokemon)
    {
        return sortByHealth(pokemon, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Pokemon[] sortByHealth(Pokemon[] pokemon, java.util.Map<String, String> context)
    {
        return _iceI_sortByHealthAsync(pokemon, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Pokemon[]> sortByHealthAsync(Pokemon[] pokemon)
    {
        return _iceI_sortByHealthAsync(pokemon, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Pokemon[]> sortByHealthAsync(Pokemon[] pokemon, java.util.Map<String, String> context)
    {
        return _iceI_sortByHealthAsync(pokemon, context, false);
    }

    /**
     * @hidden
     * @param iceP_pokemon -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Pokemon[]> _iceI_sortByHealthAsync(Pokemon[] iceP_pokemon, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Pokemon[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sortByHealth", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     PokemonSequenceHelper.write(ostr, iceP_pokemon);
                 }, istr -> {
                     Pokemon[] ret;
                     ret = PokemonSequenceHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default java.util.Map<PokemonType, Pokemon[]> groupByPokemonType(Pokemon[] pokemon)
    {
        return groupByPokemonType(pokemon, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default java.util.Map<PokemonType, Pokemon[]> groupByPokemonType(Pokemon[] pokemon, java.util.Map<String, String> context)
    {
        return _iceI_groupByPokemonTypeAsync(pokemon, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<PokemonType, Pokemon[]>> groupByPokemonTypeAsync(Pokemon[] pokemon)
    {
        return _iceI_groupByPokemonTypeAsync(pokemon, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<PokemonType, Pokemon[]>> groupByPokemonTypeAsync(Pokemon[] pokemon, java.util.Map<String, String> context)
    {
        return _iceI_groupByPokemonTypeAsync(pokemon, context, false);
    }

    /**
     * @hidden
     * @param iceP_pokemon -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.util.Map<PokemonType, Pokemon[]>> _iceI_groupByPokemonTypeAsync(Pokemon[] iceP_pokemon, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.Map<PokemonType, Pokemon[]>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "groupByPokemonType", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     PokemonSequenceHelper.write(ostr, iceP_pokemon);
                 }, istr -> {
                     java.util.Map<PokemonType, Pokemon[]> ret;
                     ret = PokemonDictionaryHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default Pokemon[] comparePokemons(Pokemon[] pokemons)
    {
        return comparePokemons(pokemons, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Pokemon[] comparePokemons(Pokemon[] pokemons, java.util.Map<String, String> context)
    {
        return _iceI_comparePokemonsAsync(pokemons, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Pokemon[]> comparePokemonsAsync(Pokemon[] pokemons)
    {
        return _iceI_comparePokemonsAsync(pokemons, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Pokemon[]> comparePokemonsAsync(Pokemon[] pokemons, java.util.Map<String, String> context)
    {
        return _iceI_comparePokemonsAsync(pokemons, context, false);
    }

    /**
     * @hidden
     * @param iceP_pokemons -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Pokemon[]> _iceI_comparePokemonsAsync(Pokemon[] iceP_pokemons, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Pokemon[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "comparePokemons", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     PokemonSequenceHelper.write(ostr, iceP_pokemons);
                 }, istr -> {
                     Pokemon[] ret;
                     ret = PokemonSequenceHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PokemonInterfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), PokemonInterfacePrx.class, _PokemonInterfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PokemonInterfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), PokemonInterfacePrx.class, _PokemonInterfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PokemonInterfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), PokemonInterfacePrx.class, _PokemonInterfacePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PokemonInterfacePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), PokemonInterfacePrx.class, _PokemonInterfacePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static PokemonInterfacePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, PokemonInterfacePrx.class, _PokemonInterfacePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static PokemonInterfacePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, PokemonInterfacePrx.class, _PokemonInterfacePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default PokemonInterfacePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (PokemonInterfacePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default PokemonInterfacePrx ice_adapterId(String newAdapterId)
    {
        return (PokemonInterfacePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default PokemonInterfacePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (PokemonInterfacePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default PokemonInterfacePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (PokemonInterfacePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default PokemonInterfacePrx ice_invocationTimeout(int newTimeout)
    {
        return (PokemonInterfacePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default PokemonInterfacePrx ice_connectionCached(boolean newCache)
    {
        return (PokemonInterfacePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default PokemonInterfacePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (PokemonInterfacePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PokemonInterfacePrx ice_secure(boolean b)
    {
        return (PokemonInterfacePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default PokemonInterfacePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (PokemonInterfacePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PokemonInterfacePrx ice_preferSecure(boolean b)
    {
        return (PokemonInterfacePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default PokemonInterfacePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (PokemonInterfacePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default PokemonInterfacePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (PokemonInterfacePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default PokemonInterfacePrx ice_collocationOptimized(boolean b)
    {
        return (PokemonInterfacePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default PokemonInterfacePrx ice_twoway()
    {
        return (PokemonInterfacePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default PokemonInterfacePrx ice_oneway()
    {
        return (PokemonInterfacePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default PokemonInterfacePrx ice_batchOneway()
    {
        return (PokemonInterfacePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default PokemonInterfacePrx ice_datagram()
    {
        return (PokemonInterfacePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default PokemonInterfacePrx ice_batchDatagram()
    {
        return (PokemonInterfacePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default PokemonInterfacePrx ice_compress(boolean co)
    {
        return (PokemonInterfacePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default PokemonInterfacePrx ice_timeout(int t)
    {
        return (PokemonInterfacePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default PokemonInterfacePrx ice_connectionId(String connectionId)
    {
        return (PokemonInterfacePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default PokemonInterfacePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (PokemonInterfacePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::DynamicPokemons::PokemonInterface";
    }
}
