//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Pokemon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DynamicPokemons;
/**
 * Helper class for marshaling/unmarshaling PokemonDictionary.
 **/

public final class PokemonDictionaryHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, java.util.Map<PokemonType, Pokemon[]> v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.size());
            for(java.util.Map.Entry<PokemonType, Pokemon[]> e : v.entrySet())
            {
                PokemonType.ice_write(ostr, e.getKey());
                PokemonSequenceHelper.write(ostr, e.getValue());
            }
        }
    }

    public static java.util.Map<PokemonType, Pokemon[]> read(com.zeroc.Ice.InputStream istr)
    {
        java.util.Map<PokemonType, Pokemon[]> v;
        v = new java.util.HashMap<DynamicPokemons.PokemonType, DynamicPokemons.Pokemon[]>();
        int sz0 = istr.readSize();
        for(int i0 = 0; i0 < sz0; i0++)
        {
            PokemonType key;
            key = PokemonType.ice_read(istr);
            Pokemon[] value;
            value = PokemonSequenceHelper.read(istr);
            v.put(key, value);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<java.util.Map<PokemonType, Pokemon[]>> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Map<PokemonType, Pokemon[]> v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            PokemonDictionaryHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<java.util.Map<PokemonType, Pokemon[]>> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            java.util.Map<PokemonType, Pokemon[]> v;
            v = PokemonDictionaryHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
