//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Pokemon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DynamicPokemons;

public interface PokemonInterface extends com.zeroc.Ice.Object
{
    Pokemon[] sortByHealth(Pokemon[] pokemon, com.zeroc.Ice.Current current);

    java.util.Map<PokemonType, Pokemon[]> groupByPokemonType(Pokemon[] pokemon, com.zeroc.Ice.Current current);

    Pokemon[] comparePokemons(Pokemon[] pokemons, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::DynamicPokemons::PokemonInterface",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::DynamicPokemons::PokemonInterface";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sortByHealth(PokemonInterface obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Pokemon[] iceP_pokemon;
        iceP_pokemon = PokemonSequenceHelper.read(istr);
        inS.endReadParams();
        Pokemon[] ret = obj.sortByHealth(iceP_pokemon, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        PokemonSequenceHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_groupByPokemonType(PokemonInterface obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Pokemon[] iceP_pokemon;
        iceP_pokemon = PokemonSequenceHelper.read(istr);
        inS.endReadParams();
        java.util.Map<PokemonType, Pokemon[]> ret = obj.groupByPokemonType(iceP_pokemon, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        PokemonDictionaryHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_comparePokemons(PokemonInterface obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Pokemon[] iceP_pokemons;
        iceP_pokemons = PokemonSequenceHelper.read(istr);
        inS.endReadParams();
        Pokemon[] ret = obj.comparePokemons(iceP_pokemons, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        PokemonSequenceHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "comparePokemons",
        "groupByPokemonType",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "sortByHealth"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_comparePokemons(this, in, current);
            }
            case 1:
            {
                return _iceD_groupByPokemonType(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_sortByHealth(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
