# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import event_pb2 as proto_dot_event__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/event_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EventServiceStub(object):
    """service to distinct on what client subscribe
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientConnects = channel.unary_unary(
                '/event.EventService/ClientConnects',
                request_serializer=proto_dot_event__pb2.ClientConnectsRequest.SerializeToString,
                response_deserializer=proto_dot_event__pb2.ClientConnectsResponse.FromString,
                _registered_method=True)
        self.ClientSubscribeLocation = channel.unary_unary(
                '/event.EventService/ClientSubscribeLocation',
                request_serializer=proto_dot_event__pb2.ClientSubscribeLocationRequest.SerializeToString,
                response_deserializer=proto_dot_event__pb2.ClientSubscribeLocationResponse.FromString,
                _registered_method=True)


class EventServiceServicer(object):
    """service to distinct on what client subscribe
    """

    def ClientConnects(self, request, context):
        """client connects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientSubscribeLocation(self, request, context):
        """client subscribe based on location
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientConnects': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientConnects,
                    request_deserializer=proto_dot_event__pb2.ClientConnectsRequest.FromString,
                    response_serializer=proto_dot_event__pb2.ClientConnectsResponse.SerializeToString,
            ),
            'ClientSubscribeLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientSubscribeLocation,
                    request_deserializer=proto_dot_event__pb2.ClientSubscribeLocationRequest.FromString,
                    response_serializer=proto_dot_event__pb2.ClientSubscribeLocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'event.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventService(object):
    """service to distinct on what client subscribe
    """

    @staticmethod
    def ClientConnects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event.EventService/ClientConnects',
            proto_dot_event__pb2.ClientConnectsRequest.SerializeToString,
            proto_dot_event__pb2.ClientConnectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientSubscribeLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/event.EventService/ClientSubscribeLocation',
            proto_dot_event__pb2.ClientSubscribeLocationRequest.SerializeToString,
            proto_dot_event__pb2.ClientSubscribeLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
