# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/event.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/event.proto\x12\x05\x65vent\"\x9f\x01\n\x05\x45vent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x1e\n\x04type\x18\x02 \x01(\x0e\x32\x10.event.EventType\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x15\n\rmax_attendees\x18\x05 \x01(\x05\x12\x15\n\rattendees_ids\x18\x06 \x03(\x05\x12!\n\x08location\x18\x07 \x01(\x0e\x32\x0f.event.Location\",\n\x15\x43lientConnectsRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\"I\n\x16\x43lientConnectsResponse\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x1c\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x0c.event.Event\"k\n\x1e\x43lientSubscribeLocationRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12!\n\x08location\x18\x03 \x01(\x0e\x32\x0f.event.Location\"g\n\x1f\x43lientSubscribeLocationResponse\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\x12!\n\x0b\x65vents_list\x18\x02 \x03(\x0b\x32\x0c.event.Event\x12\x0c\n\x04text\x18\x04 \x01(\t*H\n\tEventType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x0f\n\x0bSPORT_EVENT\x10\x01\x12\x0b\n\x07\x43ONCERT\x10\x02\x12\x0b\n\x07MEETING\x10\x03*d\n\x08Location\x12\x14\n\x10UNKNOWN_LOCATION\x10\x00\x12\n\n\x06\x43RACOW\x10\x01\x12\n\n\x06LONDON\x10\x02\x12\r\n\tSEDZISZOW\x10\x03\x12\n\n\x06ZURICH\x10\x04\x12\x0f\n\x0bLOS_ANGELES\x10\x05\x32\xcb\x01\n\x0c\x45ventService\x12O\n\x0e\x43lientConnects\x12\x1c.event.ClientConnectsRequest\x1a\x1d.event.ClientConnectsResponse\"\x00\x12j\n\x17\x43lientSubscribeLocation\x12%.event.ClientSubscribeLocationRequest\x1a&.event.ClientSubscribeLocationResponse\"\x00\x42.Z,example.com/myproject/client/myproject/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,example.com/myproject/client/myproject/proto'
  _globals['_EVENTTYPE']._serialized_start=525
  _globals['_EVENTTYPE']._serialized_end=597
  _globals['_LOCATION']._serialized_start=599
  _globals['_LOCATION']._serialized_end=699
  _globals['_EVENT']._serialized_start=29
  _globals['_EVENT']._serialized_end=188
  _globals['_CLIENTCONNECTSREQUEST']._serialized_start=190
  _globals['_CLIENTCONNECTSREQUEST']._serialized_end=234
  _globals['_CLIENTCONNECTSRESPONSE']._serialized_start=236
  _globals['_CLIENTCONNECTSRESPONSE']._serialized_end=309
  _globals['_CLIENTSUBSCRIBELOCATIONREQUEST']._serialized_start=311
  _globals['_CLIENTSUBSCRIBELOCATIONREQUEST']._serialized_end=418
  _globals['_CLIENTSUBSCRIBELOCATIONRESPONSE']._serialized_start=420
  _globals['_CLIENTSUBSCRIBELOCATIONRESPONSE']._serialized_end=523
  _globals['_EVENTSERVICE']._serialized_start=702
  _globals['_EVENTSERVICE']._serialized_end=905
# @@protoc_insertion_point(module_scope)
